package com.alexaichinger.nutritracking.model

import java.math.BigDecimal

data class MicroNutrients(
    val alcohol: BigDecimal? = null,
    val betaCarotene: BigDecimal? = null,
    val caffeine: BigDecimal? = null,
    val calcium: BigDecimal? = null,
    val cholesterol: BigDecimal? = null,
    val copper: BigDecimal? = null,
    val fructose: BigDecimal? = null,
    val galactose: BigDecimal? = null,
    val glucose: BigDecimal? = null,
    val iodine: BigDecimal? = null,
    val iron: BigDecimal? = null,
    val lactose: BigDecimal? = null,
    val magnesium: BigDecimal? = null,
    val maltose: BigDecimal? = null,
    val manganese: BigDecimal? = null,
    val pantothenicAcid: BigDecimal? = null,
    val phosphorus: BigDecimal? = null,
    val phylloquinone: BigDecimal? = null,
    val polyols: BigDecimal? = null,
    val potassium: BigDecimal? = null,
    val selenium: BigDecimal? = null,
    val starch: BigDecimal? = null,
    val sucrose: BigDecimal? = null,
    val vitaminA: BigDecimal? = null,
    val vitaminB12: BigDecimal? = null,
    val vitaminB: BigDecimal? = null,
    val vitaminB2: BigDecimal? = null,
    val vitaminB6: BigDecimal? = null,
    val vitaminB9: BigDecimal? = null,
    val vitaminC: BigDecimal? = null,
    val vitaminD: BigDecimal? = null,
    val vitaminE: BigDecimal? = null,
    val vitaminPp: BigDecimal? = null,
    val water: BigDecimal? = null,
    val zinc: BigDecimal? = null,
)
