package com.alexaichinger.nutritracking.model

import java.math.BigDecimal

data class MicroNutrients(
    var alcohol: BigDecimal,
    var betaCarotene: BigDecimal,
    var caffeine: BigDecimal,
    var calcium: BigDecimal,
    var cholesterol: BigDecimal,
    var copper: BigDecimal,
    var fructose: BigDecimal,
    var galactose: BigDecimal,
    var glucose: BigDecimal,
    var iodine: BigDecimal,
    var iron: BigDecimal,
    var lactose: BigDecimal,
    var magnesium: BigDecimal,
    var maltose: BigDecimal,
    var manganese: BigDecimal,
    var pantothenicAcid: BigDecimal,
    var phosphorus: BigDecimal,
    var phylloquinone: BigDecimal,
    var polyols: BigDecimal,
    var potassium: BigDecimal,
    var selenium: BigDecimal,
    var starch: BigDecimal,
    var sucrose: BigDecimal,
    var vitaminA: BigDecimal,
    var vitaminB12: BigDecimal,
    var vitaminB: BigDecimal,
    var vitaminB2: BigDecimal,
    var vitaminB6: BigDecimal,
    var vitaminB9: BigDecimal,
    var vitaminC: BigDecimal,
    var vitaminD: BigDecimal,
    var vitaminE: BigDecimal,
    var vitaminPp: BigDecimal,
    var water: BigDecimal,
    var zinc: BigDecimal,
)
