spring:
  application:
    name: nutri-tracking
  security:
    user:
      name: admin
      password: password
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/tracking?authSource=admin

server:
  port: ${SERVER_PORT}

# V1 API - https://world.openfoodfacts.org/files/api-documentation.html
# V2 API - https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v2/#cmp--schemas-product-nutrition
openFoodFacts:
  baseUrl: https://world.openfoodfacts.org/

logging:
  level:
    org:
      springframework:
        security: INFO