spring:
  application:
    name: nutri-tracking
  security:
    user:
      name: admin
      password: password
  data:
    mongodb:
      uri: mongodb://alex:1234@localhost:27017/tracking?authSource=admin
server:
  port: '8081'

logging:
  level:
    org:
      springframework:
        security: DEBUG