package com.alexaichinger.nutritracking.dto.internal

import java.math.BigDecimal

data class MicroNutrientsDto(
    val alcohol: BigDecimal,
    val betaCarotene: BigDecimal,
    val calcium: BigDecimal,
    val cholesterol: BigDecimal,
    val copper: BigDecimal,
    val fructose: BigDecimal,
    val galactose: BigDecimal,
    val glucose: BigDecimal,
    val iodine: BigDecimal,
    val iron: BigDecimal,
    val lactose: BigDecimal,
    val magnesium: BigDecimal,
    val maltose: BigDecimal,
    val manganese: BigDecimal,
    val pantothenicAcid: BigDecimal,
    val phosphorus: BigDecimal,
    val phylloquinone: BigDecimal,
    val polyols: BigDecimal,
    val potassium: BigDecimal,
    val selenium: BigDecimal,
    val starch: BigDecimal,
    val sucrose: BigDecimal,
    val vitaminA: BigDecimal,
    val vitaminB12: BigDecimal,
    val vitaminB: BigDecimal,
    val vitaminB2: BigDecimal,
    val vitaminB6: BigDecimal,
    val vitaminB9: BigDecimal,
    val vitaminC: BigDecimal,
    val vitaminD: BigDecimal,
    val vitaminE: BigDecimal,
    val vitaminPp: BigDecimal,
    val water: BigDecimal,
    val zinc: BigDecimal,
    val caffeine: BigDecimal,
)

fun createEmptyMicros(): MicroNutrientsDto {
    return MicroNutrientsDto(
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
        BigDecimal.ZERO,
    )
}
