services:
  nutri:
    container_name: nutri
    image: ghcr.io/alexaichinger/nutri:v${APPLICATION_VERSION}
    env_file:
      - .env
    ports:
      - 8082:${SERVER_PORT}
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_DATA_LOCATION}:/data/db/