services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: alex
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./db_data/:/data/db/